In [1]:
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
import joblib
import os

# 데이터

In [2]:
years = list(range(2014,2022))
apk_types = ['benign', 'malware']

In [3]:
df_ben_list = []
df_mal_list = []

for year in years:
    df_ben_list.append(pd.read_csv(f'./csv/{apk_types[0]}_{year}.csv', index_col=0))
    df_mal_list.append(pd.read_csv(f'./csv/{apk_types[1]}_{year}.csv', index_col=0))

In [4]:
df_ben_list[0]

Landroid/accounts/AbstractAccountAuthenticator;.getAccountRemovalAllowed:(Landroid/accounts/AccountAuthenticatorResponse;Landroid/accounts/Account;)Landroid/os/Bundle;  \
apkname                                                                                                                                                                                                                       
czech.librarymoshaf_d78b72ef2acf3775124b54718ec...                                                  0                                                                                                                         
com.app_furniturehouse.layout_F952B3F9BABD72315...                                                  0                                                                                                                         
net.ays.PROD322496_7C9144DDEB886FC20DBB3C4F5858...                                                  0                                                                                                                         
air.com.littlebigplay.games.legor6_d1da5cfa023d...                                                  0                                                                                                                         
com.kapil.mandheersinghmaan_a1d9f26acd83f80907c...                                                  0                                                                                                                         
...                                                                                               ...                                                                                                                         
com.oumugai.densityadjuster_16421666689D6626BF2...                                                  0                                                                                                                         
com.alpomag.urokijogi_3F07D70538A7B4B93F5EAC92B...                                                  0                                                                                                                         
com.candyfunkgames.A201309021F_5a36ee0887010cea...                                                  0                                                                                                                         
com.recorder.roadrecorder_993E8FCA74BAAAFA02D6B...                                                  0                                                                                                                         
com.tilapia.fartmyphone_93A02E4EDF2A1C9067BCBB8...                                                  0                                                                                                                         

                                                    Landroid/accounts/AccountManager;.addAccount:(Ljava/lang/String;Ljava/lang/String;[Ljava/lang/String;Landroid/os/Bundle;Landroid/app/Activity;Landroid/accounts/AccountManagerCallback;Landroid/os/Handler;)Landroid/accounts/AccountManagerFuture;  \
apkname                                                                                                                                                                                                                                                                                                   
czech.librarymoshaf_d78b72ef2acf3775124b54718ec...                                                  0                                                                                                                                                                                                     
com.app_furniturehouse.layout_F952B3F9BABD72315...                                                  0                                                                                                                                                          

# 모델 생성

In [5]:
model_list = []
importance_list=[]
for i, year in enumerate(years):
    train_len = int((df_ben_list[i].shape[0])*0.8)
    print(train_len)
    y_train = [1]*train_len + [0]*train_len
    x_train = pd.concat([df_ben_list[i].iloc[:train_len], df_mal_list[i].iloc[:train_len]])
    model=RandomForestClassifier(random_state=42).fit(x_train, y_train)
    model_list.append(model)
    importance_list.append(model.feature_importances_)
    print(year, 'done')

8058
2014 done
8088
2015 done
8067
2016 done
8060
2017 done
7928
2018 done
8086
2019 done
14549
2020 done
4428
2021 done


# 모델 저장

In [6]:
if not os.path.isdir('./model'):
    os.mkdir('./model')

for i, year in enumerate(years):
     joblib.dump(model_list[i] ,f'./model/model_{year}.pk1')

# 중요도 값, 랭킹 저장

In [7]:
array = np.array([1,8,5,7,9])

temp = array.argsort()*(-1)

ranks = temp.argsort()
print(array)
print(ranks)

[1 8 5 7 9]
[4 2 1 3 0]


In [8]:
array = np.array([1,8,5,7,9])

temp = array.argsort().argsort()
ranks = 5-temp
print(ranks)

[5 2 4 3 1]


In [9]:
np.array([10,5,3,1,2]).argsort()

array([3, 4, 2, 1, 0])

In [10]:
print(*enumerate(importance_list[0]))

(0, 0.0) (1, 0.0006631592369899733) (2, 1.1625204614082715e-05) (3, 2.274293351152612e-06) (4, 0.00011106445162075313) (5, 2.376988999857526e-06) (6, 0.0) (7, 0.0012795041046148037) (8, 0.00018160548237577023) (9, 0.0) (10, 0.0) (11, 0.00028150307694319385) (12, 0.0) (13, 0.00047223010610758504) (14, 0.00031312432153389745) (15, 5.710096304733549e-06) (16, 1.1276585266819258e-05) (17, 0.0011754935845877488) (18, 0.0) (19, 5.3110228472015075e-06) (20, 0.0) (21, 0.0) (22, 0.0) (23, 9.338786712227165e-06) (24, 0.0) (25, 0.0) (26, 1.998731169104461e-05) (27, 0.000172533653357587) (28, 0.0) (29, 0.0015188715074496645) (30, 0.00042077832229906647) (31, 0.0) (32, 0.0) (33, 0.0002032378533697326) (34, 0.00012614247478270787) (35, 0.0) (36, 0.00028339998778808564) (37, 0.0) (38, 0.0005321418434329822) (39, 0.0018036550704259567) (40, 0.0005082275280699091) (41, 0.00010086178203588461) (42, 8.789137090304449e-05) (43, 0.0064797537722563045) (44, 0.00018407619715183032) (45, 0.01163448120360542) 

In [11]:
rank = 1848-importance_list[0].argsort()
rank[151]

734

In [12]:
if not os.path.isdir('./feature_importance'):
    os.mkdir('./feature_importance')

for i, year in enumerate(years):

    zero_cnt = (importance_list[i]==0).sum()
    rank = 1848-importance_list[i].argsort().argsort()
    rank = np.where(rank > 1848-zero_cnt, 1848, rank)
    
    np.savetxt(f'./feature_importance/feature_importance_{year}.csv', [importance_list[i], rank], delimiter=',')